<?php 
return array( 
	"index"	=>	array(
		"name"	=>	"后台首页", 
		"key"	=>	"index", 
		"groups"	=>	array( 
			"index"	=>	array(
				"name"	=>	"后台首页", 
				"key"	=>	"index", 
				"nodes"	=>	array( 
					array("name"=>"后台首页","module"=>"Index","action"=>"main"),
					array("name"=>"后台日志","module"=>"Log","action"=>"index"),
					array("name"=>"登录日志","module"=>"Log","action"=>"user_login_log"),
					array("name"=>"访问日志","module"=>"Log","action"=>"admin_visit_log"),
					array("name"=>"删除半年前日志","module"=>"Log","action"=>"foreverdelete","show"=>false),
				),
			)
		),
	),

	"deal"	=>	array(
		"name"	=>	"借款管理", 
		"key"	=>	"deal", 
		"groups"	=>	array( 	
			"newe"	=>	array(
                "name"	=>	"★新手标",
                "key"	=>	"newe",
                "nodes"	=>	array(
                    array("name"=>"新手专享","module"=>"ExtDealNewe","action"=>"index"),
					array("name"=>"参与用户","module"=>"Loads","action"=>"newe"),
					array("name"=>"还款列表","module"=>"ExtDealNewe","action"=>"three"),
					array("name"=>"新增新手标","module"=>"ExtDealNewe","action"=>"add","show"=>false),
					array("name"=>"插入新手标","module"=>"ExtDealNewe","action"=>"insert","show"=>false),
					array("name"=>"编辑新手标","module"=>"ExtDealNewe","action"=>"edit","show"=>false),
					array("name"=>"更新新手标","module"=>"ExtDealNewe","action"=>"update","show"=>false),
					array("name"=>"导出新手标","module"=>"ExtDealNewe","action"=>"export_csv","show"=>false),
					array("name"=>"还款计划","module"=>"ExtDealNewe","action"=>"repay_plan","show"=>false),
					array("name"=>"导出还款计划","module"=>"ExtDealNewe","action"=>"export_csv_three","show"=>false),
					array("name"=>"查看详情","module"=>"ExtDealNewe","action"=>"show_detail","show"=>false),
					array("name"=>"导出投标列表","module"=>"ExtDealNewe","action"=>"do_export_load","show"=>false),
					array("name"=>"导出投标列表","module"=>"ExtDealNewe","action"=>"do_repay_plan_export_load","show"=>false),
					array("name"=>"导出所有投标列表","module"=>"ExtDealNewe","action"=>"do_allrepay_plan_export_load","show"=>false),
                ),
			),
			"uplan"	=>	array(
                "name"	=>	"★U-计划",
                "key"	=>	"uplan",
                "nodes"	=>	array(
                    array("name"=>"U计划列表","module"=>"ExtDealUplan","action"=>"index"),
					array("name"=>"参与用户","module"=>"Loads","action"=>"uplan"),
                    array("name"=>"新增U计划","module"=>"ExtDealUplan","action"=>"add","show"=>false),
                    array("name"=>"插入U计划","module"=>"ExtDealUplan","action"=>"insert","show"=>false),
                    array("name"=>"编辑U计划","module"=>"ExtDealUplan","action"=>"edit","show"=>false),
                    array("name"=>"更新U计划","module"=>"ExtDealUplan","action"=>"update","show"=>false),
					array("name"=>"导出U计划","module"=>"ExtDealUplan","action"=>"export_csv","show"=>false),
					array("name"=>"还款计划","module"=>"ExtDealUplan","action"=>"repay_plan","show"=>false),
					array("name"=>"导出还款计划","module"=>"ExtDealUplan","action"=>"export_csv_three","show"=>false),
					array("name"=>"查看详情","module"=>"ExtDealUplan","action"=>"show_detail","show"=>false),
					array("name"=>"导出投标列表","module"=>"ExtDealUplan","action"=>"do_export_load","show"=>false),
					array("name"=>"导出投标列表","module"=>"ExtDealUplan","action"=>"do_repay_plan_export_load","show"=>false),
					array("name"=>"导出所有投标列表","module"=>"ExtDealUplan","action"=>"do_allrepay_plan_export_load","show"=>false),
               ),
			),
			"deal"	=>	array(
				"name"	=>	"借款管理", 
				"key"	=>	"deal",
				"nodes"	=>	array( 
					array("name"=>"全部借款","module"=>"Deal","action"=>"index"),
					array("name"=>"常规借款","module"=>"Deal","action"=>"normal"),
					array("name"=>"审核中","module"=>"Deal","action"=>"waiting"),
					array("name"=>"审批通过","module"=>"Deal","action"=>"passed"),
					array("name"=>"已否决","module"=>"Deal","action"=>"failed"),
					array("name"=>"新增借款","module"=>"Deal","action"=>"add"),
					array("name"=>"插入借款","module"=>"Deal","action"=>"insert","show"=>false),
					array("name"=>"编辑借款","module"=>"Deal","action"=>"edit","show"=>false),
					array("name"=>"更新借款","module"=>"Deal","action"=>"update","show"=>false),
					array("name"=>"导出借款","module"=>"Deal","action"=>"export_csv","show"=>false),
					array("name"=>"删除借款","module"=>"Deal","action"=>"delete","show"=>false),
					array("name"=>"显示详情","module"=>"Deal","action"=>"show_detail","show"=>false),
					array("name"=>"投标列表","module"=>"Deal","action"=>"repay_plan_a","show"=>false),
					array("name"=>"回款计划","module"=>"Deal","action"=>"repay_plan","show"=>false),
					array("name"=>"导出投标列表","module"=>"Deal","action"=>"do_export_load","show"=>false),
					array("name"=>"导出投标列表","module"=>"Deal","action"=>"do_repay_plan_export_load","show"=>false),
					array("name"=>"导出所有投标列表","module"=>"Deal","action"=>"do_allrepay_plan_export_load","show"=>false),
					array("name"=>"导出投标记录","module"=>"Loads","action"=>"export_csv","show"=>false),
				),
			),
			"deal_c"	=>	array(
				"name"	=>	"审批管理", 
				"key"	=>	"deal_s", 
				"nodes"	=>	array( 
					array("name"=>"待审核列表","module"=>"Deal","action"=>"publish"),
					array("name"=>"复审核列表","module"=>"Deal","action"=>"true_publish"),
					array("name"=>"待三审列表","module"=>"Deal","action"=>"third_publish"),
					array("name"=>"待发布列表","module"=>"Deal","action"=>"submit_publish"),
					array("name"=>"初审","module"=>"Deal","action"=>"publish_edit","show"=>false),
					array("name"=>"初审更新","module"=>"Deal","action"=>"publish_update","show"=>false),
					array("name"=>"复审","module"=>"Deal","action"=>"true_publish_edit","show"=>false),
					array("name"=>"复审更新","module"=>"Deal","action"=>"true_publish_update","show"=>false),
					array("name"=>"三审","module"=>"Deal","action"=>"third_publish_edit","show"=>false),
					array("name"=>"三审更新","module"=>"Deal","action"=>"third_publish_update","show"=>false),
					array("name"=>"发布","module"=>"Deal","action"=>"submit_publish_edit","show"=>false),
					array("name"=>"发布更新","module"=>"Deal","action"=>"submit_publish_update","show"=>false),
				),
			),			
			"deal_s"	=>	array(
				"name"	=>	"满标管理", 
				"key"	=>	"deal_s", 
				"nodes"	=>	array( 
					array("name"=>"满标待审","module"=>"Deal","action"=>"full"),
					array("name"=>"还款中","module"=>"Deal","action"=>"inrepay"),
					array("name"=>"已还清","module"=>"Deal","action"=>"over"),
					array("name"=>"已流标","module"=>"Deal","action"=>"flow"),
					array("name"=>"满标放款","module"=>"Deal","action"=>"do_loans","show"=>false),
					array("name"=>"流标返还","module"=>"Deal","action"=>"do_received","show"=>false),
					array("name"=>"导出投标记录","module"=>"Deal","action"=>"do_export_load","show"=>false),
					array("name"=>"导出还款记录","module"=>"Deal","action"=>"export_csv_three","show"=>false),
					array("name"=>"导出逾期记录","module"=>"Deal","action"=>"export_csv_yuqi","show"=>false),
				),
			),			
			"deal_money"	=>	array(
				"name"	=>	"借贷记录", 
				"key"	=>	"deal_money", 
				"nodes"	=>	array(
					array("name"=>"待还款账单","module"=>"Deal","action"=>"three"),
					array("name"=>"逾期待收款","module"=>"Deal","action"=>"yuqi"),
					array("name"=>"网站垫付款","module"=>"Deal","action"=>"generation_repay"),
					array("name"=>"收款信息","module"=>"Deal","action"=>"user_loads_repay"),
					array("name"=>"投标详情","module"=>"Loads","action"=>"detail","show"=>false),
				),
			),
			/*
			"repay_money"	=>	array(
				"name"	=>	"理财记录", 
				"key"	=>	"repay_money", 
				"nodes"	=>	array(
					array("name"=>"待付理财单","module"=>"Repay","action"=>"three"),
					array("name"=>"逾期待付款","module"=>"Repay","action"=>"yuqi"),
					array("name"=>"网站垫付款","module"=>"Repay","action"=>"generation_repay"),
					array("name"=>"付款信息","module"=>"Repay","action"=>"user_loads_repay"),
				),
			),
			*/
			"loads"	=>	array(
				"name"	=>	"投标信息", 
				"key"	=>	"loads", 
				"nodes"	=>	array( 
					array("name"=>"投标记录","module"=>"Loads","action"=>"index"),
					array("name"=>"失败的投标","module"=>"Loads","action"=>"failed"),
					array("name"=>"导出投标记录","module"=>"Loads","action"=>"export_csv","show"=>false),
				),
			),			
			"transfer"	=>	array(
				"name"	=>	"债权转让",
				"key"	=>	"transfer",
				"nodes"	=>	array(
					array("name"=>"所有转让","module"=>"Transfer","action"=>"index"),
					array("name"=>"正在转让","module"=>"Transfer","action"=>"ing"),
					array("name"=>"成功转让","module"=>"Transfer","action"=>"success"),
					array("name"=>"撤销转让","module"=>"Transfer","action"=>"back"),
				),
			),		
		),
	),

	/*
	"prodext"	=>	array(
		"name"	=>	"产品扩展", 
		"key"	=>	"prodext", 
		"groups"	=>	array( 	
			"dreams"	=>	array(
                "name"	=>	"梦想计划",
                "key"	=>	"dreams",
                "nodes"	=>	array(
					array("name"=>"参与用户","module"=>"ExtDealDream","action"=>"index"),
                    array("name"=>"计划列表","module"=>"ExtDealDream","action"=>"items"),
                ),
			),
			"present"	=>	array(
                "name"	=>	"投资有礼",
                "key"	=>	"present",
                "nodes"	=>	array(
					array("name"=>"关联礼品U计划","module"=>"ExtDealPresent","action"=>"index"),
                    array("name"=>"参与用户","module"=>"Loads","action"=>"present"),
                    array("name"=>"还款计划","module"=>"ExtDealPresent","action"=>"three"),
                    array("name"=>"礼品列表","module"=>"ExtDealPresentGoods","action"=>"index"),
                    array("name"=>"发放记录","module"=>"ExtDealPresentGoodsOrder","action"=>"index"),
                ),
			),
		),
	),
	*/

	"user"	=>	array(
		"name"	=>	"会员管理",
		"key"	=>	"user",
		"groups"	=>	array(
			"user"	=>	array(
				"name"	=>	"会员管理",
				"key"	=>	"user",
				"nodes"	=>	array(
					array("name"=>"全部会员","module"=>"User","action"=>"all"),
					array("name"=>"VIP会员","module"=>"User","action"=>"vip"),
					array("name"=>"个人客户","module"=>"User","action"=>"index"),
					array("name"=>"企业客户","module"=>"User","action"=>"company_index"),
					array("name"=>"维护日志","module"=>"User","action"=>"visit_log"),
					array("name"=>"查看用户详情","module"=>"User","action"=>"view","show"=>false),
					array("name"=>"新增维护记录","module"=>"User","action"=>"add_visit","show"=>false),
					array("name"=>"导出会员记录","module"=>"User","action"=>"export_csv","show"=>false),
					array("name"=>"导出维护记录","module"=>"User","action"=>"export_csv_visit_log","show"=>false),
				),
			),
			"customer"	=>	array(
				"name"	=>	"会员维护",
				"key"	=>	"lock",
				"nodes"	=>	array(
					array("name"=>"会员维护","module"=>"MyCustomer","action"=>"index"),
					array("name"=>"密码锁定","module"=>"MyCustomer","action"=>"lock"),
					array("name"=>"授权中心","module"=>"MyCustomer","action"=>"authority"),
					array("name"=>"黑名单会员","module"=>"User","action"=>"black"),
					array("name"=>"会员编辑","module"=>"MyCustomer","action"=>"user_edit","show"=>false),
					array("name"=>"会员编辑更新","module"=>"MyCustomer","action"=>"user_edit_update","show"=>false),
					array("name"=>"维护推荐人","module"=>"MyCustomer","action"=>"user_referer","show"=>false),
					array("name"=>"分配客服","module"=>"MyCustomer","action"=>"user_admin","show"=>false),
					array("name"=>"分配授权中心","module"=>"MyCustomer","action"=>"user_authority","show"=>false),
					array("name"=>"重置密码","module"=>"MyCustomer","action"=>"user_reset_password","show"=>false),
					array("name"=>"密码解锁","module"=>"MyCustomer","action"=>"user_unlock_password","show"=>false),
					array("name"=>"设置黑名单","module"=>"MyCustomer","action"=>"user_black","show"=>false),
					array("name"=>"设置无效","module"=>"MyCustomer","action"=>"user_ineffect","show"=>false),
                )
			),
            "agencies"	=>	array(
                "name"	=>	"合作机构",
                "key"	=>	"agencies",
                "nodes"	=>	array(
                    array("name"=>"授权服务机构","module"=>"User","action"=>"agencies_index"),
                    array("name"=>"担保机构","module"=>"DealAgency","action"=>"index"),
                ),
            ),
            "privilege"	=>	array(
                "name"	=>	"VIP设置",
                "key"	=>	"privilege",
                "nodes"	=>	array(
                    array("name"=>"VIP等级列表","module"=>"VipType","action"=>"index"),
                    array("name"=>"VIP配置列表","module"=>"VipSetting","action"=>"index"),
                ),
            ),
		),
	),	
	
	"order"	=>	array(
		"name"	=>	"财务管理",
		"key"	=>	"order",
		"groups"	=>	array(
			"usercarry"	=>	array(
				"name"	=>	"提现管理",
				"key"	=>	"usercarry",
				"nodes"	=>	array(
					array("name"=>"提现审核","module"=>"UserCarry","action"=>"wait"),
					array("name"=>"审核通过","module"=>"UserCarry","action"=>"success"),
					array("name"=>"审核未通过","module"=>"UserCarry","action"=>"failed"),
					array("name"=>"待查询","module"=>"UserCarry","action"=>"waitquery"),
					array("name"=>"不支持的银行卡","module"=>"UserCarry","action"=>"unrec_bank"),
					array("name"=>"导出提现记录","module"=>"UserCarry","action"=>"export_csv","show"=>false),
					array("name"=>"提现审核","module"=>"UserCarry","action"=>"edit","show"=>false),
					array("name"=>"提现审核更新","module"=>"UserCarry","action"=>"update","show"=>false),
				),
			),
					
			"order"	=>	array(
				"name"	=>	"充值查询",
				"key"	=>	"order",
				"nodes"	=>	array(
					array("name"=>"全部充值","module"=>"PaymentNotice","action"=>"index"),
					array("name"=>"线上充值","module"=>"PaymentNotice","action"=>"online"),
					array("name"=>"POS充值","module"=>"PaymentNotice","action"=>"posline"),
					array("name"=>"线下充值","module"=>"PaymentNotice","action"=>"offline"),
					array("name"=>"导出充值记录","module"=>"PaymentNotice","action"=>"export_csv","show"=>false),
				),
			),					
			"moneylog"=>array(
				"name"	=>	"资金日志",
				"key"	=>	"moneylog",
				"nodes"	=>	array(
					array("name"=>"会员资金日志","module"=>"User","action"=>"fund_management"),
					array("name"=>"快速扣费日志","module"=>"User","action"=>"fund_management_deduct"),
					array("name"=>"申购期收益","module"=>"User","action"=>"fund_management_user"),
					array("name"=>"申购期利息","module"=>"User","action"=>"fund_management_wait"),
					array("name"=>"投资活动返现","module"=>"User","action"=>"fund_management_back"),
					array("name"=>"提现手续费","module"=>"User","action"=>"carry_fee"),
					array("name"=>"导出资金日志","module"=>"User","action"=>"fund_export_csv","show"=>false),
					array("name"=>"查看会员信息","module"=>"User","action"=>"view","show"=>false),
				),
			),
			"website"=>array(
				"name"	=>	"网站收益",
				"key"	=>	"website",
				"nodes"	=>	array(
					array("name"=>"网站收益日志","module"=>"Deal","action"=>"site_money"),
					array("name"=>"网站收益报表","module"=>"Deal","action"=>"site_money_report"),
					array("name"=>"导出网站收益日志","module"=>"Deal","action"=>"export_csv_site_money","show"=>false),
					array("name"=>"导出网站收益报告","module"=>"Deal","action"=>"export_csv_site_money_report","show"=>false),
				),
			),
			"hand_operated"	=>	array(
				"name"	=>	"手动操作",
				"key"	=>	"hand_operated",
				"nodes"	=>	array(
					array("name"=>"POS机充值","module"=>"User","action"=>"pos_recharge"),
					array("name"=>"快速充值","module"=>"User","action"=>"hand_recharge"),
					array("name"=>"快速扣费","module"=>"User","action"=>"hand_overdue"),
					array("name"=>"保证金冻结","module"=>"User","action"=>"hand_freeze"),
					array("name"=>"保证金记录","module"=>"User","action"=>"hand_freeze_index"),
					array("name"=>"POS机充值更新","module"=>"User","action"=>"update_pos_recharge","show"=>false),
					array("name"=>"POS机充值查询","module"=>"User","action"=>"query_pos_recharge","show"=>false),
					array("name"=>"快速充值更新","module"=>"User","action"=>"update_hand_recharge","show"=>false),
					array("name"=>"快速扣费更新","module"=>"User","action"=>"update_hand_overdue","show"=>false),
					array("name"=>"保证金冻结更新","module"=>"User","action"=>"update_hand_freeze","show"=>false),
				),
			),
			"caiwu_statistics"	=>	array(
				"name"	=>	"财务统计",
				"key"	=>	"caiwu_statistics",
				"nodes"	=>	array(
					array("name"=>"网站收益报表","module"=>"Deal","action"=>"site_money_report"),
					array("name"=>"账户余额统计表","module"=>"User","action"=>"customer_acct_list"),
					array("name"=>"用户金额统计","module"=>"User","action"=>"customer_acct_detail"),
					array("name"=>"个人帐户统计","module"=>"User","action"=>"personal_account"),
					array("name"=>"导出账户余额统计表","module"=>"User","action"=>"export_csv_customer_acct_list","show"=>false),
					array("name"=>"导出用户金额统计","module"=>"User","action"=>"export_csv_customer_acct_detail","show"=>false),
					array("name"=>"数据报表","module"=>"User","action"=>"daily_report","show"=>false),
					array("name"=>"数据汇总","module"=>"User","action"=>"account_report","show"=>false),
				),
			),
			"unusual"	=>	array(
				"name"	=>	"异常查询", 
				"key"	=>	"unusual", 
				"nodes"	=>	array(
					array("name"=>"提现异常查询","module"=>"UserCarry","action"=>"unusual"),
					array("name"=>"充值异常查询","module"=>"PaymentNotice","action"=>"unusual"),
					array("name"=>"提现密码设定","module"=>"Carry","action"=>"passset"),
					array("name"=>"提现密码更新","module"=>"Carry","action"=>"update_passset","show"=>false),
				),
			),
		),
	),
	/*	
	"Integral"	=>	array(
		"name"	=>	"积分商城",
		"key"	=>	"Integral",
		"groups"	=>	array(
			"integral_mall"	=>	array(
				"name"	=>	"积分商城",
				"key"	=>	"integral_mall",
				"nodes"	=>	array(
					array("name"=>"商品列表","module"=>"Goods","action"=>"index"),
					//array("name"=>"商品类型","module"=>"GoodsType","action"=>"index"),
					array("name"=>"商品分类","module"=>"GoodsCate","action"=>"index"),
					array("name"=>"兑换商品","module"=>"GoodsOrder","action"=>"index"),
				),
			),
		),
	),
	*/

	"front"	=>	array(
		"name"	=>	"平台推广",
		"key"	=>	"front",
		"groups"	=>	array(
			"article"	=>	array(
				"name"	=>	"文章管理",
				"key"	=>	"article",
				"nodes"	=>	array(
					array("name"=>"文章列表","module"=>"Article","action"=>"index"),
					array("name"=>"分类列表","module"=>"ArticleCate","action"=>"index"),
					array("name"=>"新增文章","module"=>"Article","action"=>"add","show"=>false),
					array("name"=>"插入文章","module"=>"Article","action"=>"insert","show"=>false),
					array("name"=>"编辑文章","module"=>"Article","action"=>"edit","show"=>false),
					array("name"=>"更新文章","module"=>"Article","action"=>"update","show"=>false),
					array("name"=>"新增分类","module"=>"ArticleCate","action"=>"add","show"=>false),
					array("name"=>"插入分类","module"=>"ArticleCate","action"=>"insert","show"=>false),
					array("name"=>"编辑分类","module"=>"ArticleCate","action"=>"edit","show"=>false),
					array("name"=>"更新分类","module"=>"ArticleCate","action"=>"update","show"=>false),
				),
			),					
			"frontconfig"	=>	array(
				"name"	=>	"前端设置",
				"key"	=>	"frontconfig",
				"nodes"	=>	array(
					array("name"=>"导航菜单列表","module"=>"Nav","action"=>"index"),
					array("name"=>"前端广告列表","module"=>"Adv","action"=>"index"),
					array("name"=>"手机端广告列表","module"=>"MAdv","action"=>"index"),
					array("name"=>"链接列表","module"=>"Link","action"=>"index"),
					array("name"=>"新增导航","module"=>"Nav","action"=>"add","show"=>false),
					array("name"=>"插入导航","module"=>"Nav","action"=>"insert","show"=>false),
					array("name"=>"编辑导航","module"=>"Nav","action"=>"edit","show"=>false),
					array("name"=>"更新导航","module"=>"Nav","action"=>"update","show"=>false),
					array("name"=>"新增前端广告","module"=>"Adv","action"=>"add","show"=>false),
					array("name"=>"插入前端广告","module"=>"Adv","action"=>"insert","show"=>false),
					array("name"=>"编辑前端广告","module"=>"Adv","action"=>"edit","show"=>false),
					array("name"=>"更新前端广告","module"=>"Adv","action"=>"update","show"=>false),
					array("name"=>"新增手机端广告","module"=>"MAdv","action"=>"add","show"=>false),
					array("name"=>"插入手机端广告","module"=>"MAdv","action"=>"insert","show"=>false),
					array("name"=>"编辑手机端广告","module"=>"MAdv","action"=>"edit","show"=>false),
					array("name"=>"更新手机端广告","module"=>"MAdv","action"=>"update","show"=>false),
					array("name"=>"新增链接","module"=>"Link","action"=>"add","show"=>false),
					array("name"=>"插入链接","module"=>"Link","action"=>"insert","show"=>false),
					array("name"=>"编辑链接","module"=>"Link","action"=>"edit","show"=>false),
					array("name"=>"更新链接","module"=>"Link","action"=>"update","show"=>false),
				),
			),
			"msgtemplate"	=>	array(
				"name"	=>	"消息模板",
				"key"	=>	"msgtemplate",
				"nodes"	=>	array(
					array("name"=>"消息模板管理","module"=>"MsgTemplate","action"=>"index"),
					array("name"=>"消息模板内容读取","module"=>"MsgTemplate","action"=>"load_tpl","show"=>false),
					array("name"=>"模板内容更新","module"=>"MsgTemplate","action"=>"update","show"=>false),
				),
			),
			"sms"	=>	array(
				"name"	=>	"短信管理", 
				"key"	=>	"sms", 
				"nodes"	=>	array( 
					array("name"=>"验证码查询","module"=>"PromoteMsg","action"=>"verify_sms"),
					array("name"=>"已发短信","module"=>"PromoteMsg","action"=>"sms"),
					array("name"=>"短信群发","module"=>"PromoteMsg","action"=>"sms_send_multi"),
					array("name"=>"短信群发结果显示","module"=>"PromoteMsg","action"=>"sms_send_multi_result","show"=>false),
				),
			),
			"message"	=>	array(
				"name"	=>	"站内消息",
				"key"	=>	"message",
				"nodes"	=>	array(
					array("name"=>"已发消息","module"=>"MsgBox","action"=>"index"),
				),
			),
		),
	),

	"department"	=>	array(
		"name"	=>	"系统管理",
		"key"	=>	"department",
		"groups"	=>	array(
			"admin_manage"	=>	array(
				"name"	=>	"用户管理",
				"key"	=>	"admin_manage",
				"nodes"	=>	array(
					array("name"=>"全部用户","module"=>"MyManager","action"=>"index"),
					array("name"=>"提成统计","module"=>"MyManager","action"=>"referrals"),
					array("name"=>"提成明细","module"=>"MyManager","action"=>"referrals_details"),
					array("name"=>"新增用户","module"=>"MyManager","action"=>"add","show"=>false),
					array("name"=>"插入用户","module"=>"MyManager","action"=>"insert","show"=>false),
					array("name"=>"编辑用户","module"=>"MyManager","action"=>"edit","show"=>false),
					array("name"=>"更新用户","module"=>"MyManager","action"=>"update","show"=>false),
					array("name"=>"删除用户","module"=>"MyManager","action"=>"delete","show"=>false),
					array("name"=>"导出用户列表","module"=>"MyManager","action"=>"export_csv","show"=>false),
					array("name"=>"导出提成统计","module"=>"MyManager","action"=>"export_referrals_csv","show"=>false),
					array("name"=>"导出提成详情","module"=>"MyManager","action"=>"export_details_csv","show"=>false),
				),
			),
			"department_manage"	=>	array(
				"name"	=>	"部门管理",
				"key"	=>	"department_manage",
				"nodes"	=>	array(
					array("name"=>"部门列表","module"=>"Departments","action"=>"index"),
					array("name"=>"角色管理","module"=>"Role","action"=>"index"),
					array("name"=>"新增部门","module"=>"Departments","action"=>"add","show"=>false),
					array("name"=>"插入部门","module"=>"Departments","action"=>"insert","show"=>false),
					array("name"=>"编辑部门","module"=>"Departments","action"=>"edit","show"=>false),
					array("name"=>"更新部门","module"=>"Departments","action"=>"update","show"=>false),
					array("name"=>"新增角色","module"=>"Role","action"=>"add","show"=>false),
					array("name"=>"插入角色","module"=>"Role","action"=>"insert","show"=>false),
					array("name"=>"编辑角色","module"=>"Role","action"=>"edit","show"=>false),
					array("name"=>"更新角色","module"=>"Role","action"=>"update","show"=>false),
					array("name"=>"删除","module"=>"Role","action"=>"delete","show"=>false),
					array("name"=>"彻底删除","module"=>"Role","action"=>"foreverdelete","show"=>false),
					array("name"=>"恢复","module"=>"Role","action"=>"restore","show"=>false),
					array("name"=>"回收站","module"=>"Role","action"=>"trash","show"=>false),
				),
			),
		),
	),

	"system"	=>	array(
		"name"	=>	"系统配置", 
		"key"	=>	"system", 
		"groups"	=>	array( 
			"sysconf"	=>	array(
				"name"	=>	"系统配置", 
				"key"	=>	"sysconf", 
				"nodes"	=>	array( 
					array("name"=>"系统配置","module"=>"Conf","action"=>"index"),
					array("name"=>"签到奖励配置","module"=>"Conf","action"=>"signin"),
					array("name"=>"邀请返利配置","module"=>"Conf","action"=>"referrals"),
					array("name"=>"扩展配置","module"=>"Conf","action"=>"extend"),
					array("name"=>"配置参数","module"=>"Conf","action"=>"params"),
					array("name"=>"新增配置","module"=>"Conf","action"=>"add","show"=>false),
					array("name"=>"插入配置","module"=>"Conf","action"=>"insert","show"=>false),
					array("name"=>"编辑配置","module"=>"Conf","action"=>"edit","show"=>false),
					array("name"=>"更新配置","module"=>"Conf","action"=>"update","show"=>false),
				),
			),
			"plat"	=>	array(
				"name"	=>	"平台设置", 
				"key"	=>	"plat", 
				"nodes"	=>	array( 
					array("name"=>"QQ客服配置","module"=>"Conf","action"=>"qq"),
					array("name"=>"手机端配置","module"=>"Conf","action"=>"mobile"),
					array("name"=>"认证类型设置","module"=>"Credit","action"=>"index"),
					array("name"=>"更新QQ客服","module"=>"Conf","action"=>"update_qq","show"=>false),
					array("name"=>"更新手机端配置","module"=>"Conf","action"=>"savemobile","show"=>false),
					array("name"=>"新增认证类型","module"=>"Credit","action"=>"add","show"=>false),
					array("name"=>"插入认证类型","module"=>"Credit","action"=>"insert","show"=>false),
					array("name"=>"编辑认证类型","module"=>"Credit","action"=>"edit","show"=>false),
					array("name"=>"更新认证类型","module"=>"Credit","action"=>"update","show"=>false),
				),
			),
			"dealconfig"	=>	array(
				"name"	=>	"借款设置", 
				"key"	=>	"dealconfig", 
				"nodes"	=>	array( 
					array("name"=>"借款产品列表","module"=>"DealCate","action"=>"index"),
					array("name"=>"借款类型设置","module"=>"DealLoanType","action"=>"index"),
					array("name"=>"合同范本设置","module"=>"Contract","action"=>"index"),
					array("name"=>"新增产品","module"=>"DealCate","action"=>"add","show"=>false),
					array("name"=>"插入产品","module"=>"DealCate","action"=>"insert","show"=>false),
					array("name"=>"编辑产品","module"=>"DealCate","action"=>"edit","show"=>false),
					array("name"=>"更新产品","module"=>"DealCate","action"=>"update","show"=>false),
					array("name"=>"新增类型","module"=>"DealLoanType","action"=>"add","show"=>false),
					array("name"=>"插入类型","module"=>"DealLoanType","action"=>"insert","show"=>false),
					array("name"=>"编辑类型","module"=>"DealLoanType","action"=>"edit","show"=>false),
					array("name"=>"更新类型","module"=>"DealLoanType","action"=>"update","show"=>false),
					array("name"=>"新增合同","module"=>"Contract","action"=>"add","show"=>false),
					array("name"=>"插入合同","module"=>"Contract","action"=>"insert","show"=>false),
					array("name"=>"编辑合同","module"=>"Contract","action"=>"edit","show"=>false),
					array("name"=>"更新合同","module"=>"Contract","action"=>"update","show"=>false),
				),
			),
			"caiwu"	=>	array(
				"name"	=>	"财务设置", 
				"key"	=>	"caiwu", 
				"nodes"	=>	array( 
					array("name"=>"提现手续费","module"=>"UserCarry","action"=>"config"),
					array("name"=>"提现银行设置","module"=>"Bank","action"=>"index"),
					array("name"=>"新增银行","module"=>"Bank","action"=>"add","show"=>false),
					array("name"=>"插入银行","module"=>"Bank","action"=>"insert","show"=>false),
					array("name"=>"编辑银行","module"=>"Bank","action"=>"edit","show"=>false),
					array("name"=>"更新银行","module"=>"Bank","action"=>"update","show"=>false),				
				),
			),
			"interface"	=>	array(
				"name"	=>	"接口设置",
				"key"	=>	"interface",
				"nodes"	=>	array(
					array("name"=>"实名认证接口","module"=>"Idcard","action"=>"index"),
					array("name"=>"支付接口设置","module"=>"Payment","action"=>"index"),
					array("name"=>"提现接口设置","module"=>"Carry","action"=>"index"),
					array("name"=>"会员第三方登录","module"=>"ApiLogin","action"=>"index"),
					array("name"=>"邮件服务器列表","module"=>"MailServer","action"=>"index"),
					array("name"=>"短信接口列表","module"=>"Sms","action"=>"index"),
					array("name"=>"安装实名认证","module"=>"Idcard","action"=>"install","show"=>false),
					array("name"=>"卸载实名认证","module"=>"Idcard","action"=>"uninstall","show"=>false),
					array("name"=>"插入实名认证","module"=>"Idcard","action"=>"insert","show"=>false),
					array("name"=>"编辑实名认证","module"=>"Idcard","action"=>"edit","show"=>false),
					array("name"=>"更新实名认证","module"=>"Idcard","action"=>"update","show"=>false),	
					array("name"=>"安装支付接口","module"=>"Payment","action"=>"install","show"=>false),
					array("name"=>"卸载支付接口","module"=>"Payment","action"=>"uninstall","show"=>false),
					array("name"=>"插入支付接口","module"=>"Payment","action"=>"insert","show"=>false),
					array("name"=>"编辑支付接口","module"=>"Payment","action"=>"edit","show"=>false),
					array("name"=>"更新支付接口","module"=>"Payment","action"=>"update","show"=>false),	
					array("name"=>"安装提现接口","module"=>"Carry","action"=>"install","show"=>false),
					array("name"=>"卸载提现接口","module"=>"Carry","action"=>"uninstall","show"=>false),
					array("name"=>"插入提现接口","module"=>"Carry","action"=>"insert","show"=>false),
					array("name"=>"编辑提现接口","module"=>"Carry","action"=>"edit","show"=>false),
					array("name"=>"更新提现接口","module"=>"Carry","action"=>"update","show"=>false),
					array("name"=>"安装第三方登录接口","module"=>"ApiLogin","action"=>"install","show"=>false),
					array("name"=>"卸载第三方登录接口","module"=>"ApiLogin","action"=>"uninstall","show"=>false),
					array("name"=>"插入第三方登录接口","module"=>"ApiLogin","action"=>"insert","show"=>false),
					array("name"=>"编辑第三方登录接口","module"=>"ApiLogin","action"=>"edit","show"=>false),
					array("name"=>"更新第三方登录接口","module"=>"ApiLogin","action"=>"update","show"=>false),
					array("name"=>"新增邮件服务器","module"=>"MailServer","action"=>"add","show"=>false),
					array("name"=>"插入邮件服务器","module"=>"MailServer","action"=>"insert","show"=>false),
					array("name"=>"编辑邮件服务器","module"=>"MailServer","action"=>"edit","show"=>false),
					array("name"=>"更新邮件服务器","module"=>"MailServer","action"=>"update","show"=>false),				
					array("name"=>"测试邮件服务器","module"=>"MailServer","action"=>"send_demo","show"=>false),
					array("name"=>"使用邮件服务器","module"=>"MailServer","action"=>"set_effect","show"=>false),
					array("name"=>"安装短信接口","module"=>"Sms","action"=>"install","show"=>false),
					array("name"=>"卸载短信接口","module"=>"Sms","action"=>"uninstall","show"=>false),
					array("name"=>"插入短信接口","module"=>"Sms","action"=>"insert","show"=>false),
					array("name"=>"编辑短信接口","module"=>"Sms","action"=>"edit","show"=>false),
					array("name"=>"更新短信接口","module"=>"Sms","action"=>"update","show"=>false),
					array("name"=>"测试短信接口","module"=>"Sms","action"=>"send_demo","show"=>false),
					array("name"=>"短信接口余额","module"=>"Sms","action"=>"check_fee","show"=>false),
					array("name"=>"短信接口账户信息","module"=>"Sms","action"=>"account_info","show"=>false),
					array("name"=>"使用短信接口","module"=>"Sms","action"=>"set_effect","show"=>false),
				),
			),
			"admin"	=>	array(
				"name"	=>	"系统管理", 
				"key"	=>	"admin", 
				"nodes"	=>	array( 
					array("name"=>"管理员管理","module"=>"Admin","action"=>"index"),
					array("name"=>"操作权限分配","module"=>"Operate","action"=>"index"),
					array("name"=>"新增管理员","module"=>"Admin","action"=>"add","show"=>false),
					array("name"=>"插入管理员","module"=>"Admin","action"=>"insert","show"=>false),
					array("name"=>"编辑管理员","module"=>"Admin","action"=>"edit","show"=>false),
					array("name"=>"更新管理员","module"=>"Admin","action"=>"update","show"=>false),				
					array("name"=>"新增权限分配","module"=>"Operate","action"=>"add","show"=>false),
					array("name"=>"插入权限分配","module"=>"Operate","action"=>"insert","show"=>false),
					array("name"=>"编辑权限分配","module"=>"Operate","action"=>"edit","show"=>false),
					array("name"=>"更新权限分配","module"=>"Operate","action"=>"update","show"=>false),				
				),
			),
			"trash"	=>	array(
				"name"	=>	"回收站", 
				"key"	=>	"trash", 
				"show"	=>	false, 
				"nodes"	=>	array( 
					array("name"=>"借款分类回收站","module"=>"DealCate","action"=>"trash"),
					array("name"=>"借款类型回收站","module"=>"DealLoanType","action"=>"trash"),
					array("name"=>"借款城市回收站","module"=>"City","action"=>"trash"),
					array("name"=>"合同范本回收站","module"=>"Contract","action"=>"trash"),
					array("name"=>"管理员角色回收站","module"=>"Role","action"=>"trash"),
					array("name"=>"文章分类回收站","module"=>"ArticleCate","action"=>"trash"),
					array("name"=>"文章回收站","module"=>"Article","action"=>"trash"),
				),
			),
		),
	),

	//市场部客服
	"customer"	=>	array(
		"name"	=>	"市场部客服",
		"key"	=>	"customer",
		"groups"	=>	array(
			"user"	=>	array(
				"name"	=>	"市场部客服",
				"key"	=>	"user",
				"nodes"	=>	array(
					array("name"=>"我的会员","module"=>"ExtAdminCustomer","action"=>"index"),
					array("name"=>"VIP会员","module"=>"ExtAdminCustomer","action"=>"vip"),
					array("name"=>"密码错误","module"=>"ExtAdminCustomer","action"=>"lock"),
					array("name"=>"维护日志","module"=>"ExtAdminCustomer","action"=>"visit_log"),
					array("name"=>"查看用户","module"=>"User","action"=>"view","show"=>false),
					array("name"=>"新增维护记录","module"=>"User","action"=>"add_visit","show"=>false),
					//array("name"=>"导出维护记录","module"=>"ExtAdminCustomer","action"=>"export_csv_visit_log","show"=>false),
					//array("name"=>"导出会员记录","module"=>"ExtAdminCustomer","action"=>"export_csv","show"=>false),
				),
			),
			"payment"	=>	array(
				"name"	=>	"充值管理",
				"key"	=>	"payment",
				"nodes"	=>	array(
					array("name"=>"所有充值","module"=>"ExtAdminCustomer","action"=>"payment"),
					array("name"=>"POS机充值","module"=>"User","action"=>"pos_recharge"),
					array("name"=>"POS机充值记录","module"=>"ExtAdminCustomer","action"=>"posline"),
					array("name"=>"POS充值更新","module"=>"User","action"=>"update_pos_recharge","show"=>false),
					array("name"=>"POS充值查询","module"=>"User","action"=>"query_pos_recharge","show"=>false),
				),
			),
			"loads"	=>	array(
				"name"	=>	"投标信息",
				"key"	=>	"loads",
				"nodes"	=>	array(
					array("name"=>"投标记录","module"=>"ExtAdminCustomer","action"=>"loads"),
					array("name"=>"回款信息","module"=>"ExtAdminCustomer","action"=>"repay"),
				),
			),
			"other"	=>	array(
				"name"	=>	"其他信息",
				"key"	=>	"other",
				"nodes"	=>	array(
					array("name"=>"提现失败","module"=>"ExtAdminCustomer","action"=>"carry_fail"),
					array("name"=>"短信验证码","module"=>"ExtAdminCustomer","action"=>"verify_sms"),
				),
			),
		),
	),

	//市场部总监/主管
	"manager"	=>	array(
		"name"	=>	"市场部管理",
		"key"	=>	"manager",
		"groups"	=>	array(
			"user"	=>	array(
				"name"	=>	"市场部管理",
				"key"	=>	"user",
				"nodes"	=>	array(
					array("name"=>"全部会员","module"=>"ExtAdminManager","action"=>"all"),
					array("name"=>"我的会员","module"=>"ExtAdminManager","action"=>"index"),
					array("name"=>"VIP会员","module"=>"ExtAdminManager","action"=>"vip"),
					array("name"=>"密码错误","module"=>"ExtAdminManager","action"=>"lock"),
					array("name"=>"维护日志","module"=>"ExtAdminManager","action"=>"visit_log"),
					array("name"=>"会员维护","module"=>"ExtAdminManager","action"=>"customer"),
					array("name"=>"查看用户","module"=>"User","action"=>"view","show"=>false),
					array("name"=>"新增维护记录","module"=>"User","action"=>"add_visit","show"=>false),
					//array("name"=>"导出维护记录","module"=>"ExtAdminManager","action"=>"export_csv_visit_log","show"=>false),
					//array("name"=>"导出会员记录","module"=>"ExtAdminManager","action"=>"export_csv","show"=>false),
					array("name"=>"分配客服","module"=>"ExtAdminManager","action"=>"user_admin","show"=>false),
					array("name"=>"重置密码","module"=>"ExtAdminManager","action"=>"user_reset_password","show"=>false),
					array("name"=>"密码解锁","module"=>"ExtAdminManager","action"=>"user_unlock_password","show"=>false),
				),
			),
			"payment"	=>	array(
				"name"	=>	"充值管理",
				"key"	=>	"payment",
				"nodes"	=>	array(
					array("name"=>"所有充值","module"=>"ExtAdminManager","action"=>"payment"),
					array("name"=>"POS机充值","module"=>"User","action"=>"pos_recharge"),
					array("name"=>"POS机充值记录","module"=>"ExtAdminManager","action"=>"posline"),
					array("name"=>"POS充值更新","module"=>"User","action"=>"update_pos_recharge","show"=>false),
					array("name"=>"POS充值查询","module"=>"User","action"=>"query_pos_recharge","show"=>false),
				),
			),
			"loads"	=>	array(
				"name"	=>	"投标信息",
				"key"	=>	"loads",
				"nodes"	=>	array(
					array("name"=>"投标记录","module"=>"ExtAdminManager","action"=>"loads"),
					array("name"=>"回款信息","module"=>"ExtAdminManager","action"=>"repay"),
				),
			),
			"other"	=>	array(
				"name"	=>	"其他信息",
				"key"	=>	"other",
				"nodes"	=>	array(
					array("name"=>"提现失败","module"=>"ExtAdminManager","action"=>"carry_fail"),
					array("name"=>"短信验证码","module"=>"ExtAdminManager","action"=>"verify_sms"),
				),
			),
		),
	),
);
?>